### ISSUE TITLE
Edits must be saved into the repository.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#36]

**Comment by ninanni** [comment]
commit: 22472880d91f4ae6534ebbc8dd7041d119529022
https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/22472880d91f4ae6534ebbc8dd7041d119529022/src/main/java/ch/uzh/ifi/hase/soprafs23/service/UserService.java#L87-L88
