### ISSUE TITLE
Provide information about the user for the client to fetch.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#37]

**Comment by ninanni** [comment]
commit: 22472880d91f4ae6534ebbc8dd7041d119529022
https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/22472880d91f4ae6534ebbc8dd7041d119529022/src/main/java/ch/uzh/ifi/hase/soprafs23/controller/UserController.java#L62-L76
