### ISSUE TITLE
The lobby having < 10 users in it  is one of two conditions to be able to join the lobby.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#55]

**Comment by ninanni** [comment]
implemented in 80e4fb308cdcec8f7c801c0805b29b6f96f8d53e
https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/80e4fb308cdcec8f7c801c0805b29b6f96f8d53e/src/main/java/ch/uzh/ifi/hase/soprafs23/service/LobbyService.java#L86-L88

**Comment by ninanni** [comment]
updated in 5466737d4ed84aa8c739f86b665a82470cf41cbe
https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/5466737d4ed84aa8c739f86b665a82470cf41cbe/src/main/java/ch/uzh/ifi/hase/soprafs23/service/LobbyService.java#L86-L88
